/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/primevue/': RouteRecordInfo<'/primevue/', '/primevue', Record<never, never>, Record<never, never>>,
    '/primevue/patterns': RouteRecordInfo<'/primevue/patterns', '/primevue/patterns', Record<never, never>, Record<never, never>>,
    '/primevue/phrases/phrases-lang': RouteRecordInfo<'/primevue/phrases/phrases-lang', '/primevue/phrases/phrases-lang', Record<never, never>, Record<never, never>>,
    '/primevue/phrases/phrases-textbook': RouteRecordInfo<'/primevue/phrases/phrases-textbook', '/primevue/phrases/phrases-textbook', Record<never, never>, Record<never, never>>,
    '/primevue/phrases/phrases-unit': RouteRecordInfo<'/primevue/phrases/phrases-unit', '/primevue/phrases/phrases-unit', Record<never, never>, Record<never, never>>,
    '/primevue/words/words-lang': RouteRecordInfo<'/primevue/words/words-lang', '/primevue/words/words-lang', Record<never, never>, Record<never, never>>,
    '/primevue/words/words-textbook': RouteRecordInfo<'/primevue/words/words-textbook', '/primevue/words/words-textbook', Record<never, never>, Record<never, never>>,
    '/primevue/words/words-unit': RouteRecordInfo<'/primevue/words/words-unit', '/primevue/words/words-unit', Record<never, never>, Record<never, never>>,
    '/quasar/': RouteRecordInfo<'/quasar/', '/quasar', Record<never, never>, Record<never, never>>,
    '/vuetify/': RouteRecordInfo<'/vuetify/', '/vuetify', Record<never, never>, Record<never, never>>,
    '/vuetify/patterns': RouteRecordInfo<'/vuetify/patterns', '/vuetify/patterns', Record<never, never>, Record<never, never>>,
    '/vuetify/phrases/phrases-lang': RouteRecordInfo<'/vuetify/phrases/phrases-lang', '/vuetify/phrases/phrases-lang', Record<never, never>, Record<never, never>>,
    '/vuetify/phrases/phrases-textbook': RouteRecordInfo<'/vuetify/phrases/phrases-textbook', '/vuetify/phrases/phrases-textbook', Record<never, never>, Record<never, never>>,
    '/vuetify/phrases/phrases-unit': RouteRecordInfo<'/vuetify/phrases/phrases-unit', '/vuetify/phrases/phrases-unit', Record<never, never>, Record<never, never>>,
    '/vuetify/settings': RouteRecordInfo<'/vuetify/settings', '/vuetify/settings', Record<never, never>, Record<never, never>>,
    '/vuetify/words/words-lang': RouteRecordInfo<'/vuetify/words/words-lang', '/vuetify/words/words-lang', Record<never, never>, Record<never, never>>,
    '/vuetify/words/words-textbook': RouteRecordInfo<'/vuetify/words/words-textbook', '/vuetify/words/words-textbook', Record<never, never>, Record<never, never>>,
    '/vuetify/words/words-unit': RouteRecordInfo<'/vuetify/words/words-unit', '/vuetify/words/words-unit', Record<never, never>, Record<never, never>>,
  }
}
