/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/element/': RouteRecordInfo<'/element/', '/element', Record<never, never>, Record<never, never>>,
    '/element/patterns4': RouteRecordInfo<'/element/patterns4', '/element/patterns4', Record<never, never>, Record<never, never>>,
    '/element/phrases-lang4': RouteRecordInfo<'/element/phrases-lang4', '/element/phrases-lang4', Record<never, never>, Record<never, never>>,
    '/element/phrases-textbook4': RouteRecordInfo<'/element/phrases-textbook4', '/element/phrases-textbook4', Record<never, never>, Record<never, never>>,
    '/element/phrases-unit4': RouteRecordInfo<'/element/phrases-unit4', '/element/phrases-unit4', Record<never, never>, Record<never, never>>,
    '/element/words-lang4': RouteRecordInfo<'/element/words-lang4', '/element/words-lang4', Record<never, never>, Record<never, never>>,
    '/element/words-textbook4': RouteRecordInfo<'/element/words-textbook4', '/element/words-textbook4', Record<never, never>, Record<never, never>>,
    '/element/words-unit4': RouteRecordInfo<'/element/words-unit4', '/element/words-unit4', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/primevue/': RouteRecordInfo<'/primevue/', '/primevue', Record<never, never>, Record<never, never>>,
    '/primevue/patterns5': RouteRecordInfo<'/primevue/patterns5', '/primevue/patterns5', Record<never, never>, Record<never, never>>,
    '/primevue/phrases-lang5': RouteRecordInfo<'/primevue/phrases-lang5', '/primevue/phrases-lang5', Record<never, never>, Record<never, never>>,
    '/primevue/phrases-textbook5': RouteRecordInfo<'/primevue/phrases-textbook5', '/primevue/phrases-textbook5', Record<never, never>, Record<never, never>>,
    '/primevue/phrases-unit5': RouteRecordInfo<'/primevue/phrases-unit5', '/primevue/phrases-unit5', Record<never, never>, Record<never, never>>,
    '/primevue/words-lang5': RouteRecordInfo<'/primevue/words-lang5', '/primevue/words-lang5', Record<never, never>, Record<never, never>>,
    '/primevue/words-textbook5': RouteRecordInfo<'/primevue/words-textbook5', '/primevue/words-textbook5', Record<never, never>, Record<never, never>>,
    '/primevue/words-unit5': RouteRecordInfo<'/primevue/words-unit5', '/primevue/words-unit5', Record<never, never>, Record<never, never>>,
    '/quasar/': RouteRecordInfo<'/quasar/', '/quasar', Record<never, never>, Record<never, never>>,
    '/quasar/patterns2': RouteRecordInfo<'/quasar/patterns2', '/quasar/patterns2', Record<never, never>, Record<never, never>>,
    '/quasar/phrases-lang2': RouteRecordInfo<'/quasar/phrases-lang2', '/quasar/phrases-lang2', Record<never, never>, Record<never, never>>,
    '/quasar/phrases-textbook2': RouteRecordInfo<'/quasar/phrases-textbook2', '/quasar/phrases-textbook2', Record<never, never>, Record<never, never>>,
    '/quasar/phrases-unit2': RouteRecordInfo<'/quasar/phrases-unit2', '/quasar/phrases-unit2', Record<never, never>, Record<never, never>>,
    '/quasar/words-lang2': RouteRecordInfo<'/quasar/words-lang2', '/quasar/words-lang2', Record<never, never>, Record<never, never>>,
    '/quasar/words-textbook2': RouteRecordInfo<'/quasar/words-textbook2', '/quasar/words-textbook2', Record<never, never>, Record<never, never>>,
    '/quasar/words-unit2': RouteRecordInfo<'/quasar/words-unit2', '/quasar/words-unit2', Record<never, never>, Record<never, never>>,
    '/vuetify/': RouteRecordInfo<'/vuetify/', '/vuetify', Record<never, never>, Record<never, never>>,
    '/vuetify/patterns': RouteRecordInfo<'/vuetify/patterns', '/vuetify/patterns', Record<never, never>, Record<never, never>>,
    '/vuetify/phrases-lang': RouteRecordInfo<'/vuetify/phrases-lang', '/vuetify/phrases-lang', Record<never, never>, Record<never, never>>,
    '/vuetify/phrases-textbook': RouteRecordInfo<'/vuetify/phrases-textbook', '/vuetify/phrases-textbook', Record<never, never>, Record<never, never>>,
    '/vuetify/phrases-unit': RouteRecordInfo<'/vuetify/phrases-unit', '/vuetify/phrases-unit', Record<never, never>, Record<never, never>>,
    '/vuetify/settings': RouteRecordInfo<'/vuetify/settings', '/vuetify/settings', Record<never, never>, Record<never, never>>,
    '/vuetify/words-lang': RouteRecordInfo<'/vuetify/words-lang', '/vuetify/words-lang', Record<never, never>, Record<never, never>>,
    '/vuetify/words-textbook': RouteRecordInfo<'/vuetify/words-textbook', '/vuetify/words-textbook', Record<never, never>, Record<never, never>>,
    '/vuetify/words-unit': RouteRecordInfo<'/vuetify/words-unit', '/vuetify/words-unit', Record<never, never>, Record<never, never>>,
  }
}
