export class MUSMappings {
  records!: MUSMapping[];
}
export class MUSMapping {
  ID = 0;
  NAME = '';
  KIND = 0;
  ENTITYID = 0;
  VALUEID = 0;
  LEVEL = 0;

  static NAME_USLANG = 'USLANG';
  static NAME_USROWSPERPAGEOPTIONS = 'USROWSPERPAGEOPTIONS';
  static NAME_USROWSPERPAGE = 'USROWSPERPAGE';
  static NAME_USLEVELCOLORS = 'USLEVELCOLORS';
  static NAME_USSCANINTERVAL = 'USSCANINTERVAL';
  static NAME_USREVIEWINTERVAL = 'USREVIEWINTERVAL';

  static NAME_USTEXTBOOK = 'USTEXTBOOK';
  static NAME_USDICTREFERENCE = 'USDICTREFERENCE';
  static NAME_USDICTNOTE = 'USDICTNOTE';
  static NAME_USDICTSREFERENCE = 'USDICTSREFERENCE';
  static NAME_USDICTTRANSLATION = 'USDICTTRANSLATION';
  static NAME_USMACVOICE = 'USMACVOICE';
  static NAME_USIOSVOICE = 'USIOSVOICE';
  static NAME_USANDROIDVOICE = 'USANDROIDVOICE';
  static NAME_USWEBVOICE = 'USWEBVOICE';
  static NAME_USWINDOWSVOICE = 'USWINDOWSVOICE';

  static NAME_USUNITFROM = 'USUNITFROM';
  static NAME_USPARTFROM = 'USPARTFROM';
  static NAME_USUNITTO = 'USUNITTO';
  static NAME_USPARTTO = 'USPARTTO';
}
